---
title: the ctd_tag app
author: Dan Kelley
---

# Files

# 01.R

A basic app, essentially a test of whether this GUI is acceptable.  Brushing is
not permitted here, either for selection or zooming.  Keystrokes are used for
both actions, and also for navigation up and down in the water column.

# 02.R

As 01.R but

1. use SA, not S
2. use CT, not theta
3. add sigma0 profile
4. add spiciness0 profile
5. show tags at focus point (if any) in status box
6. indicate database name in status box


# First-order development ideas

1. [ ] Make a function to call the app, with parameters such as
   a. [ ] directory holding files
   b. [ ] file suffix (.odf or .cnv by default)
   c. [ ] something about default scheme (for flags)
   d. [ ] name of database file
   e. [ ] etc
2. [ ] Have an interface to turn on suggested QC actions, e.g.
   a. [ ] highlight density inversions
   b. [ ] trim-to-descent
3. [ ] Have an interface to accept/reject suggested actions (and maybe record
   this in the database).

# Second-order development ideas

1. Develop a tool for exporting oce objects to relevant output formats.  This
   will need to be undertaken by someone with R expertise, SQL expertise, and of
   course expertise in writing the output format in question.

